### ISSUE TITLE
Does it run on other distributions?

### ISSUE THREAD

**Issue by hakerdefo** [dessington/vx-build#1]
This looks really neat. Does it run on other distributions or the host has to be Void Linux? BTW what packages have you included in vx-linux 5.0?

**Comment by dessington** [comment]
It's designed for Void only. I've added a package list so you can see what packages make up VX - https://github.com/dessington/vx-linux/blob/main/packages.list

**Comment by hakerdefo** [comment]
Thanks buddy :+1: 

BTW It's a great little distro you've got it going here :+1: 

Keep up the good work :+1:
